-- Keymaps are automatically loaded on the VeryLazy event
-- Default keymaps that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/keymaps.lua
-- Add any additional keymaps here

vim.keymap.set("n", "<leader>sv", ":source $MYVIMRC<cr>", { noremap = true })
vim.keymap.set("n", "<c-f>", ":Ag<space>", { noremap = true })
vim.keymap.set("n", "<leader><leader>", ":Telescope find_files<cr>", { noremap = true })
vim.keymap.set("n", "<leader>r", "<cmd>History<cr>", { noremap = true })
vim.keymap.set("n", "<leader>g", "<cmd>Telescope live_grep<cr>", { noremap = true })
vim.keymap.set("n", "<leader>F", "<cmd>Telescope git_files<cr>", { noremap = true })
vim.keymap.set("n", "<leader>co", "<cmd>Telescope lsp_document_symbols<cr>", { noremap = true })
vim.keymap.set("n", "<leader>ca", "<cmd>Telescope lsp_workspace_symbols<cr>", { noremap = true })
vim.keymap.set("n", "<leader>cg", "<cmd>Telescope diagnostics<cr>", { noremap = true })
vim.keymap.set("n", "<leader>ce", "<cmd>lua vim.lsp.buf.code_action()<CR>", { noremap = true })
vim.keymap.set("n", "<c-t>", ":tabnew<CR>", { noremap = false })
vim.keymap.set("n", "<leader>1", "1gt", { noremap = true, silent = true })
vim.keymap.set("n", "<leader>2", "2gt", { noremap = true })
vim.keymap.set("n", "<leader>3", "3gt", { noremap = true })
vim.keymap.set("n", "<leader>4", "4gt", { noremap = true })
vim.keymap.set("n", "<leader>5", "5gt", { noremap = true })
vim.keymap.set("n", "<leader>6", "6gt", { noremap = true })
vim.keymap.set("n", "<leader>7", "7gt", { noremap = true })
vim.keymap.set("n", "<leader>8", "8gt", { noremap = true })
vim.keymap.set("n", "<leader>9", "9gt", { noremap = true })
vim.keymap.set("n", "<leader>0", "0gt", { noremap = true })
vim.keymap.set("n", "mF", ":MixFormat<cr>", { noremap = true })
vim.keymap.set("n", "qp", vim.cmd.cprev, { desc = "Go to the previous item in the quickfix list." })
vim.keymap.set("n", "qn", vim.cmd.cnext, { desc = "Go to the next item in the quickfix list." })
vim.keymap.set("n", "qq", vim.cmd.ccl, { desc = "Close quickfix list" })
